# Generated by Django 5.0 on 2023-12-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/%Y/%m/%d')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('date_hired', models.DateTimeField(auto_now_add=True)),
                ('top_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
