# Generated by Django 5.0 on 2023-12-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='top_seller',
            new_name='is_top_seller',
        ),
    ]
