# Generated by Django 5.0.1 on 2024-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_sqft_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Townhouse', 'Townhouse'), ('Land', 'Land'), ('Office', 'Office')], default='House', max_length=50),
        ),
    ]
