# Generated by Django 5.0 on 2023-12-26 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0002_rename_top_seller_realtor_is_top_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sale_type', models.CharField(choices=[('for sale', 'for sale'), ('for rent', 'for rent')], default='for sale', max_length=15)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('home_type', models.CharField(choices=[('house', 'house'), ('apartment', 'apartment')], default='house', max_length=15)),
                ('size', models.IntegerField()),
                ('open_house', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(upload_to='listings/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_7', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_8', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_9', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_10', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_11', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_12', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_13', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_14', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_15', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_16', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_17', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_18', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_19', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('photo_20', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
